language: python
python:
    - "3.7"

install:
    - pip install poetry
    - poetry install
    - cp env-template .env
script:
    - poetry run flask db init
    - poetry run flask db migrate
    - poetry run flask db upgrade
    - poetry run python -m pytest --cov database
    - poetry run coverage-badge -o coverage.svg
after_success:
    - echo "upload to some server..."
