language: python
python:
    - "3.7"

install:
    - pip install poetry
    - poetry install
    - cp env-template .env
script:
    - pyflakes member_database
    - poetry run flask db upgrade
    - poetry run python -m pytest --cov database
    - poetry run coverage-badge -o coverage.svg
after_success:
    - curl -u "$badge_upload_user:$badge_upload_password" -T coverage.svg "$badge_upload_url"
