language: python
python:
    - "3.7"

install:
    - pip install poetry
    - poetry install
script:
    - poetry run python -m pytest --cov database
    - poetry run coverage-badge -o coverage.svg
after_success:
    - echo "upload to some server..."
